CREATE TABLE T1 (c1 JSON, c2 INTEGER);
CREATE TABLE T2 (c1 REAL NOT NULL DEFAULT NULL, c2 REAL);
CREATE TABLE T3 (c2 REAL);
SELECT (SELECT ROW_NUMBER() OVER (ORDER BY c.c2) FROM T3 LIMIT 1), DENSE_RANK() OVER (ORDER BY a.c2) FROM T1 AS a INNER JOIN T2 AS b ON a.c1 = b.c2 INNER JOIN T3 AS c ON b.c1 = c.c2 GROUP BY a.c2